from pathlib import Path
from html import escape

ROOT=Path(__file__).resolve().parents[1]

LANGS={
'es':{'folder':'spanish','name':'Español','young':'Guía inicial para jóvenes acompañantes de conversación','care':'Guía inicial para cuidadores','situations':'¿Qué hago cuando...?','activities':'Formas de conectar','ycard':'Tarjeta de conversación para jóvenes','ccard':'Tarjeta de comunicación para cuidadores','download':'Descargar PDF','mode':'Modalidad'},
'zh':{'folder':'mandarin','name':'普通话','young':'青年交流伙伴入门指南','care':'照护者入门指南','situations':'遇到这种情况怎么办？','activities':'建立联结的方法','ycard':'青年伙伴交流提示卡','ccard':'照护者沟通提示卡','download':'下载 PDF','mode':'类型'}}

SITUATIONS={
'es':[('repeating-story','Repite la misma historia'),('cannot-remember-name','No recuerda mi nombre'),('cannot-find-word','No encuentra una palabra'),('seems-incorrect','Dice algo que parece incorrecto'),('no-answer','No responde'),('conversation-stops','La conversación se detiene'),('seems-confused','Parece confundido/a'),('frustrated','Se frustra'),('lose-interest','Pierde el interés'),('refuse-activity','Rechaza una actividad'),('seems-tired','Parece cansado/a'),('emotional','Se emociona o se angustia'),('cannot-understand','No logro entender'),('same-question','Hace la misma pregunta'),('nothing-to-say','No sé qué decir')],
'zh':[('repeating-story','反复讲同一个故事'),('cannot-remember-name','记不起我的名字'),('cannot-find-word','想不起某个词'),('seems-incorrect','说的内容似乎不对'),('no-answer','没有回应'),('conversation-stops','谈话停了下来'),('seems-confused','看起来很困惑'),('frustrated','感到挫败'),('lose-interest','失去兴趣'),('refuse-activity','拒绝活动'),('seems-tired','看起来很疲倦'),('emotional','情绪激动或难过'),('cannot-understand','我听不明白'),('same-question','反复问同一个问题'),('nothing-to-say','我不知道说什么')]}

ACTIVITIES={
'es':[('family','Familia y personas importantes'),('music','Música'),('sports','Deportes'),('food','Comida y cocina'),('travel','Viajes y lugares'),('gardening','Jardinería y naturaleza'),('art','Arte y creatividad'),('objects','Objetos significativos'),('traditions','Tradiciones y celebraciones'),('movies','Películas y televisión'),('work','Trabajo y habilidades'),('school','Escuela y juventud')],
'zh':[('family','家人与重要的人'),('music','音乐'),('sports','体育运动'),('food','食物与烹饪'),('travel','旅行与地方'),('gardening','园艺与自然'),('art','艺术与创作'),('objects','有意义的物品'),('traditions','传统与节庆'),('movies','电影与电视'),('work','工作与技能'),('school','学校与年轻时光')]}

START={
'es':{
'young':[('Cómo puede cambiar la conversación con la demencia','Puede resultar difícil encontrar palabras, mantener la atención, recordar detalles o seguir varias ideas. Los cambios varían según la persona y el día.','El humor, las emociones, las preferencias, las habilidades, la identidad y el deseo de conectar pueden permanecer. Vea primero a la persona, no el diagnóstico.'),('Su papel','Usted no es médico, examinador ni cuidador sustituto. Su función es crear un intercambio cómodo y respetuoso.','La relación es mutua: escuche con atención, comparta algo de usted y permita que la persona mayor también guíe.'),('Prepárese','Conozca el nombre preferido, idioma, intereses y estilo de comunicación. Lleve dos temas, una actividad opcional y una alternativa familiar.','Revise ruido, luz, cámara y privacidad. Si el plan no ayuda, déjelo a un lado.'),('Comience con calma','Preséntese con claridad, haga una observación sencilla y formule una sola pregunta a la vez.','Dé tiempo para responder. No empiece poniendo a prueba la memoria con “¿se acuerda de mí?”.'),('Mantenga la conversación','Siga el nombre, lugar, interés o recuerdo que despierte energía. Haga una pregunta de seguimiento amable.','Si una pregunta abierta cuesta, ofrezca dos opciones sencillas. Acepte el silencio y deje espacio para sus preguntas.'),('Memoria y repetición','Ofrezca la información con naturalidad y no corrija cada error. Responda a la emoción y al sentido general.','Si vuelve la misma historia, escuche con respeto y explore otro detalle, sentimiento o relación.'),('Use actividades','Fotos, música, objetos conocidos, dibujo o movimiento pueden abrir una conversación; terminar la tarea no es la meta.','Si no hay interés, simplifique, cambie o pare. No hay puntuación, prisa ni respuesta correcta.'),('Cierre bien','Avise que la conversación terminará, resuma un momento agradable y agradezca el tiempo compartido.','Anote brevemente qué despertó interés para facilitar una conexión futura.')],
'care':[('Comunicación centrada en la persona','La comunicación es parte del cuidado, no una tarea adicional. Empiece por la identidad, preferencias, capacidades y ritmo de la persona.','Pregunte cómo desea que se le llame y observe qué entorno favorece su participación.'),('Antes de hablar','Acérquese de frente, póngase a una altura cómoda, consiga su atención y reduzca el ruido.','Revise audífonos, lentes, dolor, hambre, sed, cansancio y necesidad de ir al baño.'),('Lenguaje claro y adulto','Use frases breves, una idea a la vez y palabras familiares. Hable como adulto con adulto.','Evite infantilizar, hablar demasiado fuerte o discutir delante de la persona como si no estuviera.'),('Dé tiempo','Después de hablar, espere. Repetir enseguida puede interrumpir una respuesta que está formándose.','Observe mirada, gesto, postura y tono; la respuesta no siempre llega en palabras.'),('Apoye la elección','Ofrezca dos opciones reales y muestre los objetos cuando ayude. Respete el “no” siempre que sea seguro.','Divida las instrucciones en pasos y reconozca cada intento, no solo el resultado.'),('Responda a la emoción','Primero reconozca la emoción: miedo, preocupación, orgullo, tristeza o alegría.','No es necesario corregir cada detalle para transmitir seguridad y respeto.'),('Repetición y memoria','Responda con calma y use señales visibles, rutinas y recordatorios sencillos.','Pregúntese qué necesidad puede expresar la repetición: orientación, consuelo, dolor o incertidumbre.'),('Actividades con sentido','Parta de intereses, cultura, trabajo, familia y hábitos. Invite; no imponga.','Adapte el nivel de apoyo para que la persona pueda contribuir y decidir.'),('Cuando aumenta la tensión','Baje el ritmo, use menos palabras, dé espacio y cambie una sola cosa del ambiente.','Si existe riesgo inmediato, siga el plan de seguridad y pida apoyo.'),('Comunicación en equipo','Registre qué palabras, enfoques y temas ayudan o dificultan. Comparta información concreta con el siguiente cuidador.','Proteja la privacidad y evite etiquetas que definan a la persona por una conducta.'),('Cambios repentinos','Un cambio súbito de comunicación, alerta o conducta puede necesitar atención clínica.','Informe por la vía habitual y documente qué cambió, cuándo y qué observó.'),('Cuídese y reflexione','Las conversaciones difíciles pueden afectar al cuidador. Haga una pausa segura y busque apoyo cuando lo necesite.','Revise qué funcionó y pruebe un ajuste pequeño la próxima vez.')]},
'zh':{
'young':[('失智症可能怎样影响交流','找词、集中注意、记住细节、跟上多重话题或保持原有速度，可能会变得困难。每个人、每一天都不一样。','幽默感、情感、喜好、能力、身份认同和联结的愿望仍可能保留。先看见这个人，而不是诊断。'),('您的角色','您不是医生、考官，也不是替代照护者。您的任务是营造轻松、尊重的交流。','关系是双向的：认真倾听，适当地分享自己，也让长者带领谈话。'),('提前准备','了解对方喜欢的称呼、语言、兴趣和交流方式。准备两个话题、一个可选活动和一个熟悉的备用话题。','检查噪声、光线、摄像头和隐私。如果计划没有帮助，就把它放下。'),('从容开始','清楚地介绍自己，从一个简单观察开始，一次只问一个问题。','留出回答时间。不要一开始就用“您记得我吗？”来考验记忆。'),('让谈话继续','留意哪个名字、地方、兴趣或回忆让对方有精神，再温和地追问一句。','开放式问题太难时，可给两个简单选择。接纳安静，也给对方提问的空间。'),('记忆与重复','自然地补充信息，不必纠正每个错误。回应情感和整体意思。','同一个故事再次出现时，仍然尊重地倾听，并探索另一个细节、感受或关系。'),('借助活动','照片、音乐、熟悉的物品、绘画或动作都能打开话题；完成任务不是目标。','如果对方没有兴趣，就简化、更换或停止。没有分数、速度或标准答案。'),('好好结束','提前说明谈话快要结束，回顾一个愉快时刻，并感谢共同度过的时间。','简要记下什么引起了兴趣，方便下次继续联结。')],
'care':[('以人为本的交流','交流是照护的一部分，不是额外任务。先了解对方的身份、喜好、能力和节奏。','询问喜欢的称呼，并观察什么环境最有利于参与。'),('开口之前','从正面靠近，保持舒适的视线高度，先获得注意，并减少噪声。','检查助听器、眼镜、疼痛、饥渴、疲劳和如厕需要。'),('清楚而成人化的语言','句子简短，一次表达一个意思，使用熟悉的词。保持成人对成人的语气。','不要把对方当小孩、过度提高音量，或当着本人谈论本人。'),('留出时间','说完后等待。马上重复可能打断正在形成的回答。','观察眼神、手势、姿势和语气；回应不一定都是语言。'),('支持选择','提供两个真实选项，必要时把物品展示出来。在安全允许时尊重“不”。','把指令分成小步骤，并认可每一次尝试，而不只是结果。'),('回应情绪','先承认情绪，例如害怕、担心、自豪、悲伤或快乐。','为了传达安全与尊重，不必纠正每一个细节。'),('重复与记忆','平静回应，使用可见提示、固定流程和简单提醒。','想一想重复是否在表达某种需要：方向感、安慰、疼痛或不确定。'),('有意义的活动','从兴趣、文化、工作、家庭和习惯出发。邀请参与，不要强迫。','调整支持程度，让对方能够贡献、选择和决定。'),('紧张升级时','放慢速度，减少语言，留出空间，一次只改变一个环境因素。','如果存在即时风险，请依照安全流程寻求支援。'),('团队沟通','记录哪些用词、方法和话题有帮助或造成困难，并把具体信息交给下一位照护者。','保护隐私，避免用某个行为给一个人贴标签。'),('突然变化','交流、清醒程度或行为突然改变，可能需要临床评估。','依照正常渠道报告，并记录变化内容、时间和观察到的情况。'),('照顾自己并反思','困难的交流也会影响照护者。需要时先安全暂停并寻求支持。','回顾什么有效，下次尝试一个小调整。')]}}

def write(path,text):
    p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')

def shell(code,title,body,depth=2):
    back='../'*depth
    disclaimer=('Este recurso práctico apoya la comunicación y la conexión; no sustituye el consejo médico.' if code=='es' else '本实用资源用于支持交流与联结，不能替代医疗建议。')
    return f'<!doctype html><html lang="{code}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} — Sage &amp; Seed</title><link rel="stylesheet" href="{back}assets/css/site.css"><link rel="stylesheet" href="{back}assets/css/resources.css"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="{back}index.html"><img src="{back}assets/images/logo.png" alt=""><span>Sage &amp; Seed</span></a><nav class="nav"><a href="{back}guides.html">English</a><a href="{back}guides-more-languages.html">Español · 普通话 · भारतीय भाषाएँ</a></nav></div></header><main>{body}</main><footer class="site-footer"><div class="container"><p>{disclaimer}</p></div></footer></body></html>'

for code,L in LANGS.items():
    folder=L['folder']; base=f'guides/{folder}'; nums=('1','2','3','4') if code=='es' else ('一','二','三','四')
    for who in ('young','care'):
        title=L[who]; chapters=START[code][who]
        sections=''.join(f'<section class="guide-chapter"><h2>{h}</h2><p>{a}</p><p>{b}</p></section>' for h,a,b in chapters)
        evidence=('<h2>Base de evidencia</h2><div class="notice">Basado en revisiones sistemáticas y síntesis de evidencia. El objetivo es apoyar la comunicación, la dignidad y la conexión significativa, no ofrecer tratamiento.</div>' if code=='es' else '<h2>证据基础</h2><div class="notice">内容参考系统综述与证据综合，重点是支持交流、尊严与有意义的联结，而不是提供治疗。</div>')
        pdf=f'../../assets/downloads/guides/{folder}/sage-seed-{"young-adult" if who=="young" else "caregiver"}-guide-{code}.pdf'
        body=f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["name"]} · {L["mode"]} {nums[0]}</p><h1>{title}</h1><a class="button" href="{pdf}" download>{L["download"]}</a></div></section><section class="section"><div class="container prose">{sections}{evidence}</div></section>'
        write(f'{base}/{"young-adult-starter" if who=="young" else "caregiver-starter"}.html',shell(code,title,body))
    cards=''.join(f'<article class="card"><h3>{name}</h3><p>{"Una respuesta calmada y respetuosa protege la conexión." if code=="es" else "平静、尊重的回应能够保护彼此的联结。"}</p><a href="../../situations/{folder}/{slug}.html">{L["situations"]} →</a></article>' for slug,name in SITUATIONS[code])
    write(f'{base}/situations.html',shell(code,L['situations'],f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["name"]} · {L["mode"]} {nums[1]}</p><h1>{L["situations"]}</h1><a class="button" href="../../assets/downloads/situation-guides/{folder}/sage-seed-situation-guides-{code}.pdf" download>{L["download"]}</a></div></section><section class="section"><div class="container grid three">{cards}</div></section>'))
    for slug,name in SITUATIONS[code]:
        if code=='es': parts=[('Qué puede estar pasando',f'“{name}” puede reflejar cambios de memoria, lenguaje, atención, cansancio, emoción o un entorno demasiado exigente.'),('Qué hacer','Baje el ritmo, use una idea a la vez y dé tiempo. Reconozca la emoción antes de corregir información.'),('Algo que puede decir','“Está bien, no hay prisa. Podemos verlo juntos.”'),('Evite','No examine la memoria, discuta, avergüence, infantilice ni hable de la persona como si no estuviera.'),('Observe','Fíjese en ruido, dolor, hambre, fatiga, expresión facial, postura y en qué tema devuelve la calma.'),('Si no funciona','Simplifique, ofrezca dos opciones, cambie de tema o haga una pausa. Si el cambio es súbito o preocupante, siga la vía habitual de apoyo clínico.')]
        else: parts=[('可能发生了什么',f'“{name}”可能与记忆、语言、注意力、疲劳、情绪变化或环境要求过高有关。'),('可以怎么做','放慢速度，一次只表达一个意思并留出时间。先回应情绪，再考虑是否需要补充事实。'),('可以这样说','“没关系，不着急。我们可以一起看看。”'),('尽量避免','不要考验记忆、争辩、羞辱、幼儿化，也不要当着本人谈论本人。'),('留意什么','留意噪声、疼痛、饥饿、疲劳、面部表情、姿势，以及什么话题能让对方恢复平静。'),('仍然没有帮助时','简化内容、提供两个选择、换个话题或暂停。如果变化突然或令人担忧，请依照正常渠道寻求临床支持。')]
        body=f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["mode"]} {nums[1]}</p><h1>{name}</h1></div></section><section class="section"><div class="container prose">'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in parts)+'</div></section>'
        write(f'situations/{folder}/{slug}.html',shell(code,name,body))
    cards=''.join(f'<article class="card"><h3>{name}</h3><p>{"Use un interés familiar para invitar, no para examinar." if code=="es" else "用熟悉的兴趣发出邀请，而不是进行考验。"}</p><a href="../../activities/{folder}/{slug}.html">{L["activities"]} →</a></article>' for slug,name in ACTIVITIES[code])
    write(f'{base}/activities.html',shell(code,L['activities'],f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["name"]} · {L["mode"]} {nums[2]}</p><h1>{L["activities"]}</h1><a class="button" href="../../assets/downloads/activities/{folder}/sage-seed-ways-to-connect-{code}.pdf" download>{L["download"]}</a></div></section><section class="section"><div class="container grid three">{cards}</div></section>'))
    for slug,name in ACTIVITIES[code]:
        if code=='es': parts=[('Por qué puede ayudar',f'{name} puede reducir la presión de inventar un tema y abrir espacio para historias, opiniones y disfrute compartido.'),('Preparación','Elija de dos a cuatro fotos grandes, un objeto conocido o una breve muestra. Compruebe permiso y comodidad.'),('Empiece suavemente','Pregunte: “¿Qué le llama la atención?” o “¿Lo vemos juntos?”.'),('Mantenga el intercambio','Haga una pregunta a la vez sobre personas, lugares, sentidos, rutinas u opiniones. Comparta también algo suyo.'),('Siga la chispa','Observe respuestas más largas, preguntas, sonrisas, gestos, tarareo o el regreso a un detalle.'),('Personalice',f'Use el idioma, cultura, época, vecindario, trabajo, familia y preferencias concretas de la persona relacionadas con {name.lower()}.'),('Simplifique','Muestre una sola imagen, haga una observación u ofrezca dos opciones. Mirar juntos en silencio también cuenta.'),('No lo convierta en examen','No exija nombres, fechas, letras, puntuaciones ni respuestas correctas. Ofrezca la información libremente.'),('Para la próxima vez','Traiga una foto, canción, objeto o historia relacionada con la respuesta de hoy.')]
        else: parts=[('为什么可能有帮助',f'{name}能够减少寻找新话题的压力，为故事、意见和共同的愉快体验留出空间。'),('准备','选择两到四张清晰的大照片、一个熟悉物品或一段简短素材。先确认对方愿意并感到舒适。'),('轻松开始','可以问：“您先注意到什么？”或“我们一起看看好吗？”'),('让交流继续','一次只问一个有关人物、地点、感官、日常习惯或看法的问题，也分享一点自己的经历。'),('抓住兴趣的火花','留意更长的回答、提问、微笑、手势、哼唱，或反复回到某个细节。'),('个性化',f'结合对方的语言、文化、年代、社区、工作、家庭，以及对{name}的具体喜好。'),('简化','只展示一张图片，做一个观察，或给出两个选择。安静地一起看也很有意义。'),('不要变成考试','不要要求说出姓名、日期、歌词、分数或标准答案。需要的信息可以自然地提供。'),('下次继续','根据今天的回应，带来一张相关照片、一首歌、一个物品或一个故事。')]
        body=f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["mode"]} {nums[2]}</p><h1>{name}</h1></div></section><section class="section"><div class="container prose">'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in parts)+'</div></section>'
        write(f'activities/{folder}/{slug}.html',shell(code,name,body))
    yitems=(['Sonría, preséntese y use el nombre preferido.','Una pregunta a la vez; dé tiempo para responder.','Siga lo que despierta interés.','Comparta también algo de usted.','Nada de exámenes, discusión, prisa ni presión.','Simplifique, ofrezca opciones o cambie de rumbo.','La conexión importa más que una respuesta correcta.'] if code=='es' else ['微笑、介绍自己，并使用对方喜欢的称呼。','一次问一个问题，留出回答时间。','跟随能够引起兴趣的话题。','也适当地分享自己。','不要考试、争辩、催促或施压。','简化、提供选择或改变方向。','联结比正确答案更重要。'])
    citems=(['Acérquese con calma y consiga la atención.','Una idea o instrucción a la vez.','Dé más tiempo y use palabras familiares.','Observe rostro y lenguaje corporal.','Mantenga opciones y reconozca la emoción.','Reduzca el ruido; use rutinas u objetos conocidos.','Anote lo que ayudó para el siguiente cuidador.','Informe cambios repentinos y preocupantes por la vía habitual.'] if code=='es' else ['平静地靠近并先获得注意。','一次表达一个意思或指令。','留出更多时间，使用熟悉词语。','观察面部表情和身体语言。','保留选择，并承认对方的情绪。','减少噪声，使用熟悉的流程或物品。','记录有效方法，交给下一位照护者。','按正常渠道报告突然且令人担忧的变化。'])
    for who,items in [('young',yitems),('care',citems)]:
        title=L['ycard'] if who=='young' else L['ccard']; fn='young-adult-conversation' if who=='young' else 'caregiver-communication'
        body=f'<section class="page-hero"><div class="container"><p class="eyebrow">{L["name"]} · {L["mode"]} {nums[3]}</p><h1>{title}</h1><a class="button" href="../../assets/downloads/cards/{folder}/sage-seed-{fn}-card-{code}.pdf" download>{L["download"]}</a></div></section><section class="section"><div class="container"><article class="worksheet pocket-card"><ul class="check-list">'+''.join(f'<li>{x}</li>' for x in items)+'</ul></article></div></section>'
        write(f'{base}/{"young-adult-card" if who=="young" else "caregiver-card"}.html',shell(code,title,body))
print('Generated Spanish and Mandarin resources.')
exec(compile((ROOT/'tools/normalize_site_links.py').read_text(encoding='utf-8'), str(ROOT/'tools/normalize_site_links.py'), 'exec'))
