from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
header='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Sage &amp; Seed</title><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/resources.css"></head><body><header class="site-header"><div class="container nav-wrap"><a class="brand" href="index.html"><img src="assets/images/logo.png" alt=""><span>Sage &amp; Seed</span></a><button class="menu-toggle" aria-expanded="false">Menu</button><nav class="nav"><a href="how-it-works.html">How it works</a><a aria-current="page" href="guides.html">Guides &amp; Resources</a><a href="for-young-adults.html">Young adults</a><a href="caregivers.html">Caregivers</a><a href="research.html">Research</a></nav></div></header><main>'''
footer='''</main><footer class="site-footer"><div class="container"><p>Practical, evidence-informed resources for respectful connection.</p></div></footer><script src="assets/js/site.js"></script></body></html>'''

english='''<section class="section" id="english"><div class="container"><p class="eyebrow">English training guides</p><h2>Four modes, one practical system</h2><div class="grid four"><article class="card resource-mode"><div class="icon">1</div><p class="eyebrow">Mode 1</p><h3>Starter Booklets</h3><p>Build understanding and confidence.</p><a href="guides/english/young-adult-starter.html">Young adult</a> · <a href="guides/english/caregiver-starter.html">Caregiver</a></article><article class="card resource-mode"><div class="icon">2</div><p class="eyebrow">Mode 2</p><h3>Situation Guides</h3><p>Know what to try in difficult moments.</p><a href="guides/english/situations.html">View all 15</a></article><article class="card resource-mode"><div class="icon">3</div><p class="eyebrow">Mode 3</p><h3>Activity &amp; Passion Guides</h3><p>Use familiar interests to open conversation.</p><a href="guides/english/activities.html">View all 12</a></article><article class="card resource-mode"><div class="icon">4</div><p class="eyebrow">Mode 4</p><h3>Always-With-You Cards</h3><p>Keep essential prompts nearby.</p><a href="guides/english/young-adult-card.html">Young adult</a> · <a href="guides/english/caregiver-card.html">Caregiver</a></article></div></div></section>'''
chooser='''<section class="section tint" id="languages"><div class="container"><p class="eyebrow">More languages</p><h2>Choose a language</h2><p>Every language includes all four training modes and downloadable PDFs.</p><div class="grid two language-groups"><div class="card"><h3>Spanish and Mandarin</h3><div class="language-tabs"><a class="button" href="guides-more-languages.html#spanish">Español</a><a class="button" href="guides-more-languages.html#mandarin">普通话</a></div></div><div class="card"><h3>Indian languages</h3><div class="language-tabs"><a class="button" href="guides-more-languages.html#hindi">हिंदी</a><a class="button" href="guides-more-languages.html#kannada">ಕನ್ನಡ</a><a class="button" href="guides-more-languages.html#marathi">मराठी</a><a class="button" href="guides-more-languages.html#bengali">বাংলা</a></div></div></div></div></section>'''
downloads='''<section class="section" id="downloads"><div class="container"><h2>English PDF downloads</h2><div class="grid three"><a class="card" download href="assets/downloads/guides/english/sage-seed-young-adult-guide-en.pdf">Young Adult Starter Guide</a><a class="card" download href="assets/downloads/guides/english/sage-seed-caregiver-guide-en.pdf">Caregiver Starter Guide</a><a class="card" download href="assets/downloads/situation-guides/english/sage-seed-situation-guides-en.pdf">Situation Guide Collection</a><a class="card" download href="assets/downloads/activities/english/sage-seed-ways-to-connect-en.pdf">Ways to Connect</a><a class="card" download href="assets/downloads/cards/english/sage-seed-young-adult-conversation-card-en.pdf">Young Adult Card</a><a class="card" download href="assets/downloads/cards/english/sage-seed-caregiver-communication-card-en.pdf">Caregiver Card</a></div></div></section>'''
main=header.format(title='Guides & Resources')+'''<section class="page-hero"><div class="container"><p class="eyebrow">Guides &amp; Resources</p><h1>Practical guides for better connection</h1><p>English guides are below. Choose another language for the same complete four-mode training system.</p><a class="button" href="#languages">Choose another language</a></div></section>'''+english+chooser+downloads+footer
(ROOT/'guides.html').write_text(main,encoding='utf-8')

langs=[
('spanish','Español','spanish','es','Guías de formación en español','Guías iniciales','Guías por situación','Actividades e intereses','Tarjetas rápidas'),
('mandarin','普通话','mandarin','zh','普通话培训指南','入门指南','情境指南','活动与兴趣','随身提示卡'),
('hindi','हिंदी','hindi','hi','हिंदी प्रशिक्षण सामग्री','स्टार्टर गाइड','स्थिति गाइड','एक्टिविटी गाइड','साथ रखने वाले कार्ड'),
('kannada','ಕನ್ನಡ','kannada','kn','ಕನ್ನಡ ತರಬೇತಿ ಗೈಡ್‌ಗಳು','ಆರಂಭಿಕ ಗೈಡ್‌ಗಳು','ಸನ್ನಿವೇಶ ಗೈಡ್‌ಗಳು','ಆಕ್ಟಿವಿಟಿ ಗೈಡ್‌ಗಳು','ಜೊತೆಯಲ್ಲಿ ಇಟ್ಟುಕೊಳ್ಳುವ ಕಾರ್ಡ್‌ಗಳು'),
('marathi','मराठी','marathi','mr','मराठी प्रशिक्षण मार्गदर्शिका','सुरुवातीच्या मार्गदर्शिका','परिस्थिती मार्गदर्शिका','अॅक्टिव्हिटी मार्गदर्शिका','जवळ ठेवायची कार्डे'),
('bengali','বাংলা','bengali','bn','বাংলা প্রশিক্ষণ গাইড','শুরুর গাইড','পরিস্থিতি গাইড','অ্যাক্টিভিটি গাইড','সঙ্গে রাখার কার্ড')]
sections=[]
link_text={
'es':('Jóvenes','Cuidadores','Ver las 15 guías','Ver las 12 guías','Descargas PDF','Guía para jóvenes','Guía para cuidadores','Guías por situación','Guías de actividades','Tarjeta para jóvenes','Tarjeta para cuidadores'),
'zh':('青年伙伴','照护者','查看全部 15 篇','查看全部 12 篇','PDF 下载','青年伙伴指南','照护者指南','情境指南','活动指南','青年伙伴提示卡','照护者提示卡'),
'hi':('युवा साथी','केयरगिवर','सभी 15 गाइड देखें','सभी 12 गाइड देखें','पीडीएफ डाउनलोड','युवा साथी गाइड','केयरगिवर गाइड','स्थिति गाइड','एक्टिविटी गाइड','युवा साथी कार्ड','केयरगिवर कार्ड'),
'kn':('ಯುವ ಸಂಗಾತಿ','ಕೇರ್‌ಗಿವರ್','ಎಲ್ಲಾ 15 ಗೈಡ್‌ಗಳನ್ನು ನೋಡಿ','ಎಲ್ಲಾ 12 ಗೈಡ್‌ಗಳನ್ನು ನೋಡಿ','ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್‌ಗಳು','ಯುವ ಸಂಗಾತಿ ಗೈಡ್','ಕೇರ್‌ಗಿವರ್ ಗೈಡ್','ಸನ್ನಿವೇಶ ಗೈಡ್‌ಗಳು','ಆಕ್ಟಿವಿಟಿ ಗೈಡ್‌ಗಳು','ಯುವ ಸಂಗಾತಿ ಕಾರ್ಡ್','ಕೇರ್‌ಗಿವರ್ ಕಾರ್ಡ್'),
'mr':('तरुण साथी','केअरगिव्हर','सर्व 15 मार्गदर्शिका पाहा','सर्व 12 मार्गदर्शिका पाहा','पीडीएफ डाउनलोड','तरुण साथीची मार्गदर्शिका','केअरगिव्हर मार्गदर्शिका','परिस्थिती मार्गदर्शिका','अॅक्टिव्हिटी मार्गदर्शिका','तरुण साथीचे कार्ड','केअरगिव्हर कार्ड'),
'bn':('তরুণ সঙ্গী','কেয়ারগিভার','সব ১৫টি গাইড দেখুন','সব ১২টি গাইড দেখুন','পিডিএফ ডাউনলোড','তরুণ সঙ্গীর গাইড','কেয়ারগিভার গাইড','পরিস্থিতি গাইড','অ্যাক্টিভিটি গাইড','তরুণ সঙ্গীর কার্ড','কেয়ারগিভার কার্ড')}
for anchor,label,folder,code,heading,m1,m2,m3,m4 in langs:
    ya,cg,all15,all12,pdfs,yguide,cguide,sguides,aguides,ycard,ccard=link_text[code]
    sections.append(f'''<section class="section {'tint' if len(sections)%2 else ''}" id="{anchor}"><div class="container"><p class="eyebrow">{label}</p><h2>{heading}</h2><div class="grid four"><article class="card"><div class="icon">1</div><h3>{m1}</h3><a href="guides/{folder}/young-adult-starter.html">{ya}</a> · <a href="guides/{folder}/caregiver-starter.html">{cg}</a></article><article class="card"><div class="icon">2</div><h3>{m2}</h3><a href="guides/{folder}/situations.html">{all15}</a></article><article class="card"><div class="icon">3</div><h3>{m3}</h3><a href="guides/{folder}/activities.html">{all12}</a></article><article class="card"><div class="icon">4</div><h3>{m4}</h3><a href="guides/{folder}/young-adult-card.html">{ya}</a> · <a href="guides/{folder}/caregiver-card.html">{cg}</a></article></div><details class="download-panel"><summary>{pdfs}</summary><div class="grid three"><a download href="assets/downloads/guides/{folder}/sage-seed-young-adult-guide-{code}.pdf">{yguide}</a><a download href="assets/downloads/guides/{folder}/sage-seed-caregiver-guide-{code}.pdf">{cguide}</a><a download href="assets/downloads/situation-guides/{folder}/sage-seed-situation-guides-{code}.pdf">{sguides}</a><a download href="assets/downloads/activities/{folder}/sage-seed-ways-to-connect-{code}.pdf">{aguides}</a><a download href="assets/downloads/cards/{folder}/sage-seed-young-adult-conversation-card-{code}.pdf">{ycard}</a><a download href="assets/downloads/cards/{folder}/sage-seed-caregiver-communication-card-{code}.pdf">{ccard}</a></div></details></div></section>''')
more=header.format(title='Guides in More Languages')+'''<section class="page-hero"><div class="container"><a href="guides.html">← English guides</a><p class="eyebrow">Complete translated collections</p><h1>Training guides in six additional languages</h1><div class="language-tabs"><a href="#spanish">Español</a><a href="#mandarin">普通话</a><a href="#hindi">हिंदी</a><a href="#kannada">ಕನ್ನಡ</a><a href="#marathi">मराठी</a><a href="#bengali">বাংলা</a></div></div></section>'''+''.join(sections)+footer
(ROOT/'guides-more-languages.html').write_text(more,encoding='utf-8')
print('Rebuilt language hubs.')
exec(compile((ROOT/'tools/normalize_site_links.py').read_text(encoding='utf-8'), str(ROOT/'tools/normalize_site_links.py'), 'exec'))
